(lang dune 3.16)

(name runtime)

(generate_opam_files true)

(source
 (github p1onerka/antlr4-OCamlTarget))

(authors "Ksenia Kotelnikova")

(maintainers "Ksenia Kotelnikova")

(package
 (name runtime)
 (synopsis "runtime module for ANTLR")
 (description "OCaml runtime module for ANTLR")
 (depends ocaml dune (ocamlformat :build))
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
