name: Lint and Format OCaml Code

on:
  push:
    branches:
      - dev

env:
  OPAMROOT: /home/user/.opam
  OPAMCONFIRMLEVEL: unsafe-yes

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    container:
      image: kakadu18/ocaml:fp2024

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installing dependencies
        run: |
          sudo apt-get update
          opam update
          opam install ocamlformat --deps-only --yes
          opam install zanuda --yes

      - name: Format code with ocamlformat
        run: |
          opam exec -- ocamlformat --version
          opam exec -- ocamlformat --inplace $(find . -name "*.ml" -or -name "*.mli")

      - name: Run zanuda linter
        run: |
          opam exec -- zanuda -dir . -add-prefix src/ > zanuda_report.txt

      - name: Upload linter artifact
        uses: actions/upload-artifact@v4
        with:
          name: zanuda_report
          path: zanuda_report.txt